package com.tj.thirstyCatWeb.entity;

import java.util.Calendar;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

//Maps to DB table: drink

@Entity
public class Drink {

	//The below two annotations make the top value the primary key & auto generate it
	@Id
	@GeneratedValue
	private long id;
	private Calendar startTime;
	private Calendar endTime;
	
	//Protected constructor - not sure why to use this, look this up
	protected Drink() {
		
	}
	
	//Constructor (takes start & end time as arguments; id is autogenerated)
	public Drink(Calendar startTime, Calendar endTime) {
		super();
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public long getId() {
		return id;
	}

	public Calendar getStartTime() {
		return startTime;
	}

	public Calendar getEndTime() {
		return endTime;
	}

	@Override
	public String toString() {
		return "Drink [id=" + id + ", startTime=" + startTime + ", endTime=" + endTime + "]";
	}
	
}
