# Generated by Django 2.1.3 on 2018-12-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('photo_path', models.CharField(max_length=256)),
                ('drinks_today', models.IntegerField(default=0)),
            ],
        ),
    ]
