# Generated by Django 2.1.4 on 2018-12-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drinks_today',
            new_name='drinksToday',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='photo_path',
            new_name='photoPath',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='time_end',
            new_name='timeEnd',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='time_start',
            new_name='timeStart',
        ),
    ]
